name: Valgrind

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unit_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: sudo apt install build-essential libcunit1 libcunit1-doc libcunit1-dev
    - name: make
      run: make
    - name: make test
      run: make test && bin/utils_test
